### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by qustavo** [qustavo/sqlhooks#11]
Benchmarks show a 2x and 3x overhead (mysql and psql). This should decrease.

**Comment by keegancsmith** [comment]
I think a good change would be to change the API to pass args as `[]driver.NamedValue` rather than `[]interface{}`.

**Comment by gchaincl** [comment]
That might work, it's a trade-off between performance and API simplicity, WDYT?

**Comment by keegancsmith** [comment]
You can export the convenience function `namedToInterface` to simplify it for users. You could even take an existing `Hooks` and convert it to a `FastHooks` (where `FastHooks` takes the `[]driver.NamedValue`).

But this should be tested/profiled first. It may be due to the different paths `database/sql` takes based on the interfaces `sqlhooks.Conn` implements. For example if the benchmark did a `db.Exec` instead of a `db.Query` then after my recent PR you should notice it being a lot faster.

**Comment by gchaincl** [comment]
That makes a lot of sense, I totally agree with your approach

**Comment by CarbonFactory** [comment]
Any update on the above discussion?

**Comment by gchaincl** [comment]
I haven't been able to try it, but FastHooks makes lot of sense to me. What's your use case and how do you think it could be improved?

**Comment by gchaincl** [comment]
ping @CarbonFactory

**Comment by CarbonFactory** [comment]
Hello, sorry did not notice the reply. I'm executing few big stored procedures and want to log the timings. Seeing the issue that the performance could be improved, I wanted to know if it is going to be implemented or not. As I don't want to add extra overhead on the already slower queries.

Also, I want to populate the Audit columns such as CreatedBy/Date and UpdatedBy/Date using a hook. 
Is that even possible?  Currently, I'm doing it manually for each SQL as I want to stay away from the bulky ORMs :D

**Comment by gchaincl** [comment]
If your use case is to execute long stored procedures, then the overhead imposed by sqlhook should be negligible.

**Comment by keegancsmith** [comment]
sqlhooks doesn't let you do that right now + doing this in this layer would require parsing the SQL query. TBH it doesn't sound appropriate for sqlhooks pkg, and also sounds like a tricky path to follow if you forked sqlhooks to do your bidding. Can you not rely on db hooks / update your queries.

**Comment by surki** [comment]
@qustavo btw, the perf numbers in the README are not up to date, can we please update them?
From previous discussion [here](https://github.com/qustavo/sqlhooks/pull/23#issuecomment-465145566), the overhead is very minimal/negligible now.

**Comment by qustavo** [comment]
Sure, would you mind opening a PR with the update?
