### ISSUE TITLE
when using wraper driver, table name has  Double quotes

### ISSUE THREAD

**Issue by huangyong-170207** [qustavo/sqlhooks#54]
when using wraper dierver, code like this:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/113108834/191086204-84c281af-6190-404f-85d0-efc4444117dc.png">
sql exec err for table name has double quotes,
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/113108834/191086066-e9489a9e-696b-440e-be3a-be9062153877.png">

when not using wraper, code like this
<img width="747" alt="image" src="https://user-images.githubusercontent.com/113108834/191086390-e82d4886-501c-49f0-b3ed-b7224194a8cc.png">
sql exec success, table name change ok
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/113108834/191086571-882cce76-2938-4daf-a11f-d802329efc04.png">

so, what is the problem?

**Comment by qustavo** [comment]
not sure if that's a gorm related issue though, did you try it with sqlite/postgres?
